### ISSUE TITLE
Add Composer

### ISSUE THREAD

**Issue by peterkokot** [joshualion/Schuger#1]
Hello, I would suggest to add Composer and publish it also on packagist.org:
http://getcomposer.org

**Comment by Maikuolan** [comment]
This is definitely a good idea. :+1: 

If you need help in doing this, I recommend reading the **[Basic usage](https://getcomposer.org/doc/01-basic-usage.md#composer-json-project-setup)** documentation for Composer, to gain a better understanding of how to add Composer to your project (and how to create a `composer.json` file).

The Composer package itself has a `composer.json` file you can look at (although, it's a little more complicated than necessary, so, may be daunting if you've never used Composer before):

https://github.com/composer/composer/blob/master/composer.json

I use Composer for most of my projects here on GitHub; My `composer.json` files are much simpler and smaller than the main Composer package `composer.json` file, so, if you wanted a simpler example, you could look at some of those, too:

https://github.com/Maikuolan/phpMussel/blob/master/composer.json
https://github.com/Maikuolan/CIDRAM/blob/master/composer.json
https://github.com/Maikuolan/SFS-Mass-IP-Checker/blob/master/composer.json

After you've created your `composer.json` file, you can register your project package with **[Packagist](https://packagist.org/)**, to allow Composer users to automatically download and install your package.

**Comment by jtreminio** [comment]
I'm sorry why was I added to this repo?

**Comment by peterkokot** [comment]
Well, idea for maybe one day in the future then...
